# naema_data.py — Nomenclature NAEMA Rev1 complète (Sections, Divisions, Groupes)
# Source: AFRISTAT — NAEMA Rev1 (2011), conforme CITI Rev4

SECTIONS = {
    "A": "Agriculture, Sylviculture, Pêche",
    "B": "Activités Extractives",
    "C": "Activités de Fabrication",
    "D": "Production et Distribution d'Électricité et de Gaz",
    "E": "Production et Distribution d'Eau, Assainissement, Traitement des Déchets et Dépollution",
    "F": "Construction",
    "G": "Commerce",
    "H": "Transports et Entreposage",
    "I": "Hébergement et Restauration",
    "J": "Information et Communication",
    "K": "Activités Financières et d'Assurance",
    "L": "Activités Immobilières",
    "M": "Activités Spécialisées, Scientifiques et Techniques",
    "N": "Activités de Services de Soutien et de Bureau",
    "O": "Activités d'Administration Publique",
    "P": "Enseignement",
    "Q": "Activités pour la Santé Humaine et l'Action Sociale",
    "R": "Activités Artistiques, Sportives et Récréatives",
    "S": "Autres Activités de Services n.c.a.",
    "T": "Activités Spéciales des Ménages",
    "U": "Activités des Organisations Extraterritoriales",
}

# Division code → (Section letter, Division label)
DIVISIONS = {
    "01": ("A", "Agriculture, Élevage, Chasse et Activités de Soutien"),
    "02": ("A", "Sylviculture, Exploitation Forestière et Activités de Soutien"),
    "03": ("A", "Pêche, Pisciculture, Aquaculture"),
    "05": ("B", "Extraction de Charbon et de Lignite"),
    "06": ("B", "Extraction d'Hydrocarbures"),
    "07": ("B", "Extraction de Minerais Métalliques"),
    "08": ("B", "Autres Activités Extractives"),
    "09": ("B", "Activités de Soutien aux Industries Extractives"),
    "10": ("C", "Fabrication de Produits Alimentaires"),
    "11": ("C", "Fabrication de Boissons"),
    "12": ("C", "Fabrication de Produits à Base de Tabac"),
    "13": ("C", "Activités de Fabrication de Textiles"),
    "14": ("C", "Fabrication d'Articles d'Habillement"),
    "15": ("C", "Travail du Cuir ; Fabrication d'Articles de Voyage et de Chaussures"),
    "16": ("C", "Travail du Bois et Fabrication d'Articles en Bois hors Meubles"),
    "17": ("C", "Fabrication du Papier et du Carton"),
    "18": ("C", "Imprimerie et Reproduction d'Enregistrements"),
    "19": ("C", "Raffinage Pétrolier, Cokéfaction"),
    "20": ("C", "Fabrication de Produits Chimiques"),
    "21": ("C", "Fabrication de Produits Pharmaceutiques"),
    "22": ("C", "Travail du Caoutchouc et du Plastique"),
    "23": ("C", "Fabrication de Matériaux Minéraux"),
    "24": ("C", "Métallurgie"),
    "25": ("C", "Fabrication d'Ouvrages en Métaux"),
    "26": ("C", "Fabrication de Produits Électroniques et Informatiques"),
    "27": ("C", "Fabrication d'Équipements Électriques"),
    "28": ("C", "Fabrication de Machines et d'Équipements n.c.a."),
    "29": ("C", "Construction de Véhicules Automobiles"),
    "30": ("C", "Fabrication d'Autres Matériels de Transport"),
    "31": ("C", "Fabrication de Meubles et Matelas"),
    "32": ("C", "Autres Industries Manufacturières"),
    "33": ("C", "Réparation et Installation de Machines et d'Équipements Professionnels"),
    "35": ("D", "Production et Distribution d'Électricité et de Gaz"),
    "36": ("E", "Captage, Traitement et Distribution d'Eau"),
    "37": ("E", "Collecte et Traitement des Eaux Usées"),
    "38": ("E", "Collecte, Traitement et Élimination des Déchets ; Récupération"),
    "39": ("E", "Dépollution et Autres Activités de Gestion des Déchets"),
    "41": ("F", "Construction de Bâtiments"),
    "42": ("F", "Génie Civil"),
    "43": ("F", "Activités Spécialisées de Construction"),
    "45": ("G", "Commerce et Réparation d'Automobiles et de Motocycles"),
    "46": ("G", "Commerce de Gros et Activités des Intermédiaires"),
    "47": ("G", "Commerce de Détail"),
    "49": ("H", "Transports Terrestres"),
    "50": ("H", "Transports par Eau"),
    "51": ("H", "Transports Aériens"),
    "52": ("H", "Entreposage et Activités des Auxiliaires de Transport"),
    "53": ("H", "Activités de Poste et de Courrier"),
    "55": ("I", "Hébergement"),
    "56": ("I", "Restauration et Débits de Boissons"),
    "58": ("J", "Édition"),
    "59": ("J", "Production Audio et Vidéo : Télévision, Cinéma, Son"),
    "60": ("J", "Programmation Télévisuelle ; Radiodiffusion"),
    "61": ("J", "Télécommunications"),
    "62": ("J", "Activités Informatiques : Conseil, Programmation"),
    "63": ("J", "Activités de Fourniture d'Information"),
    "64": ("K", "Activités Financières"),
    "65": ("K", "Assurance"),
    "66": ("K", "Activités d'Auxiliaires Financiers et d'Assurance"),
    "68": ("L", "Activités Immobilières"),
    "69": ("M", "Activités Juridiques et Comptables"),
    "70": ("M", "Activités des Sièges Sociaux ; Conseil en Gestion"),
    "71": ("M", "Activités d'Architecture, d'Ingénierie et Techniques"),
    "72": ("M", "Recherche-Développement"),
    "73": ("M", "Publicité et Études de Marché"),
    "74": ("M", "Autres Activités Professionnelles de Services Spécialisés"),
    "75": ("M", "Activités Vétérinaires"),
    "77": ("N", "Location et Location-Bail"),
    "78": ("N", "Activités liées aux Ressources Humaines"),
    "79": ("N", "Activités des Agences de Réservation et Voyagistes"),
    "80": ("N", "Enquêtes et Sécurité"),
    "81": ("N", "Soutien aux Bâtiments ; Aménagement Paysager"),
    "82": ("N", "Activités de Soutien aux Entreprises ; Activités de Bureau"),
    "84": ("O", "Activités d'Administration Publique"),
    "85": ("P", "Enseignement"),
    "86": ("Q", "Activités pour la Santé Humaine"),
    "87": ("Q", "Activités d'Hébergement Médico-Social et Social"),
    "88": ("Q", "Action Sociale sans Hébergement"),
    "90": ("R", "Activités Créatives, Artistiques et de Spectacle"),
    "91": ("R", "Conservation et Valorisation du Patrimoine"),
    "92": ("R", "Organisation de Jeux de Hasard et d'Argent"),
    "93": ("R", "Activités Sportives, Récréatives et de Loisirs"),
    "94": ("S", "Activités des Organisations Associatives"),
    "95": ("S", "Réparation d'Ordinateurs, Biens Personnels et Domestiques"),
    "96": ("S", "Fourniture d'Autres Services Personnels"),
    "97": ("T", "Activités des Ménages en tant qu'Employeurs de Personnel Domestique"),
    "98": ("T", "Activités Indifférenciées Autoproduites des Ménages"),
    "99": ("U", "Activités des Organisations Extraterritoriales"),
}

# Group code → Group label (organized by division)
GROUPS = {
    # ── Section A : Agriculture, Sylviculture, Pêche ──
    "01.1": "Culture de céréales et autres cultures n.c.a.",
    "01.2": "Culture de légumes ; pépinière ; horticulture",
    "01.3": "Culture de fruits, de noix, de plantes pour boisson ou épices",
    "01.4": "Élevage",
    "01.5": "Culture et élevage associés",
    "01.6": "Activités de soutien à la culture et à l'élevage",
    "01.7": "Chasse et activités annexes",
    "02.1": "Sylviculture et exploitation forestière",
    "02.2": "Cueillette",
    "02.3": "Activités forestières de soutien",
    "03.0": "Pêche, pisciculture, aquaculture",
    # ── Section B : Activités Extractives ──
    "05.0": "Extraction de charbon et de lignite",
    "06.0": "Extraction d'hydrocarbures",
    "07.1": "Extraction de minerais de fer",
    "07.2": "Extraction de minerais de métaux non ferreux",
    "08.1": "Extraction de pierres, de sables et d'argiles",
    "08.2": "Activités extractives n.c.a.",
    "09.0": "Activités de soutien aux industries extractives",
    # ── Section C : Activités de Fabrication ──
    "10.1": "Abattage, transformation et conservation des viandes",
    "10.2": "Transformation et conservation des poissons, crustacés et mollusques",
    "10.3": "Transformation et conservation des fruits et légumes",
    "10.4": "Fabrication de corps gras d'origine animale et végétale",
    "10.5": "Fabrication de produits laitiers et de glaces",
    "10.6": "Travail des grains ; fabrication de produits amylacés",
    "10.7": "Fabrication de produits alimentaires à base de céréales n.c.a.",
    "10.8": "Fabrication d'aliments pour animaux",
    "10.9": "Fabrication d'autres produits alimentaires",
    "11.0": "Fabrication de boissons",
    "12.0": "Fabrication de produits à base de tabac",
    "13.1": "Filature, tissage et ennoblissement textile",
    "13.2": "Fabrication d'articles textiles non vestimentaires",
    "14.0": "Fabrication d'articles d'habillement",
    "15.1": "Travail du cuir ; fabrication d'articles de voyage",
    "15.2": "Fabrication de chaussures",
    "16.1": "Sciage et rabotage du bois",
    "16.2": "Fabrication d'articles en bois, liège, vannerie et sparterie (hors meubles)",
    "17.0": "Fabrication de pâte à papier, de papier et de carton",
    "18.1": "Imprimerie et activités connexes",
    "18.2": "Reproduction d'enregistrements",
    "19.1": "Raffinage pétrolier",
    "19.2": "Cokéfaction",
    "20.1": "Fabrication de produits chimiques de base",
    "20.2": "Fabrication de produits chimiques fonctionnels",
    "21.0": "Fabrication de produits pharmaceutiques",
    "22.1": "Travail du caoutchouc",
    "22.2": "Travail du plastique",
    "23.1": "Fabrication de verre et d'articles en verre",
    "23.2": "Fabrication de produits céramiques",
    "23.3": "Fabrication de ciments et autres produits minéraux",
    "24.1": "Sidérurgie et première transformation de l'acier",
    "24.2": "Métallurgie et première transformation des métaux non ferreux",
    "24.3": "Fonderie",
    "25.1": "Fabrication de structures métalliques, citernes et ouvrages chaudronnés",
    "25.2": "Fabrication d'autres ouvrages en métaux",
    "26.1": "Fabrication de composants électroniques, d'ordinateurs et de périphériques",
    "26.2": "Fabrication d'équipements de communication et de produits électroniques grand public",
    "26.3": "Fabrication d'équipements d'imagerie médicale, de précision, d'optique et d'horlogerie",
    "27.1": "Fabrication de machines et matériels électrotechniques",
    "27.2": "Fabrication d'appareils domestiques",
    "28.1": "Fabrication de machines d'usage général",
    "28.2": "Fabrication de machines d'usage spécifique",
    "29.0": "Construction de véhicules automobiles",
    "30.1": "Construction navale, aéronautique et ferroviaire",
    "30.2": "Fabrication d'autres équipements de transport",
    "31.0": "Fabrication de meubles et matelas",
    "32.0": "Autres industries manufacturières",
    "33.1": "Réparation de machines et d'équipements professionnels",
    "33.2": "Installation de machines et d'équipements professionnels",
    # ── Section D : Électricité et Gaz ──
    "35.1": "Production, transport et distribution d'électricité",
    "35.2": "Production et distribution de combustibles gazeux et de glace",
    # ── Section E : Eau, Assainissement, Déchets ──
    "36.0": "Captage, traitement et distribution d'eau",
    "37.0": "Collecte et traitement des eaux usées",
    "38.0": "Collecte, traitement et élimination des déchets ; récupération",
    "39.0": "Dépollution et autres activités de gestion des déchets",
    # ── Section F : Construction ──
    "41.1": "Promotion immobilière",
    "41.2": "Construction de bâtiments complets",
    "42.0": "Génie civil",
    "43.0": "Activités spécialisées de construction",
    # ── Section G : Commerce ──
    "45.1": "Commerce de véhicules automobiles",
    "45.2": "Entretien et réparation de véhicules automobiles",
    "45.3": "Commerce de pièces détachées et d'accessoires automobiles",
    "45.4": "Commerce et réparation de motocycles",
    "46.1": "Activités des intermédiaires du commerce de gros",
    "46.2": "Commerce de gros de produits agricoles bruts, d'animaux vivants, produits alimentaires, boissons et tabac",
    "46.3": "Commerce de gros de biens de consommation non alimentaires",
    "46.4": "Commerce de gros de produits intermédiaires non agricoles",
    "46.5": "Commerce de gros de machines, d'équipements et fournitures",
    "46.6": "Commerce de gros non spécialisé",
    "47.1": "Commerce de détail en magasin non spécialisé",
    "47.2": "Commerce de détail en magasin spécialisé",
    "47.3": "Commerce de détail hors magasin",
    # ── Section H : Transports et Entreposage ──
    "49.1": "Transports ferroviaires",
    "49.2": "Transports routiers",
    "49.3": "Transports par conduites",
    "50.1": "Transports maritimes et côtiers",
    "50.2": "Transports fluviaux",
    "51.0": "Transports aériens",
    "52.1": "Entreposage",
    "52.2": "Activités des auxiliaires de transport",
    "53.0": "Activités de poste et de courrier",
    # ── Section I : Hébergement et Restauration ──
    "55.0": "Hébergement",
    "56.1": "Restauration",
    "56.2": "Débits de boissons",
    # ── Section J : Information et Communication ──
    "58.1": "Édition de livres et périodiques et autres activités d'édition",
    "58.2": "Édition de logiciels",
    "59.1": "Production vidéo : cinéma et télévision",
    "59.2": "Production audio et édition musicale",
    "60.0": "Programmation télévisuelle ; radiodiffusion",
    "61.0": "Télécommunications",
    "62.0": "Activités informatiques : conseil, programmation",
    "63.0": "Activités de fourniture d'information",
    # ── Section K : Activités Financières et d'Assurance ──
    "64.1": "Intermédiation monétaire",
    "64.2": "Activités des fonds de placements, holdings et similaires",
    "64.3": "Activités de crédit non monétaire",
    "65.1": "Assurance vie et capitalisation",
    "65.2": "Assurance non-vie (IARD)",
    "65.3": "Réassurance",
    "66.1": "Activités d'auxiliaires financiers",
    "66.2": "Activités d'auxiliaires d'assurance",
    "66.3": "Gestion de fonds",
    # ── Section L : Activités Immobilières ──
    "68.1": "Activités immobilières sur biens propres",
    "68.2": "Activités des agences immobilières et gestion pour compte de tiers",
    # ── Section M : Activités Spécialisées, Scientifiques et Techniques ──
    "69.1": "Activités juridiques",
    "69.2": "Activités comptables",
    "70.1": "Activités des sièges sociaux",
    "70.2": "Conseil de gestion",
    "71.1": "Activités d'architecture et d'ingénierie",
    "71.2": "Activités de contrôle et analyses techniques",
    "72.1": "Recherche-développement en sciences physiques et naturelles",
    "72.2": "Recherche-développement en sciences sociales et humaines",
    "73.1": "Publicité",
    "73.2": "Études de marché et sondages",
    "74.0": "Autres activités professionnelles de services spécialisés",
    "75.0": "Activités vétérinaires",
    # ── Section N : Activités de Services de Soutien et de Bureau ──
    "77.1": "Location de matériels de transport",
    "77.2": "Location de biens personnels et domestiques",
    "77.3": "Location de machines, d'équipements et de biens divers",
    "78.0": "Activités liées aux ressources humaines",
    "79.0": "Activités des agences de réservation et voyagistes",
    "80.0": "Enquêtes et sécurité",
    "81.1": "Services combinés de soutien lié aux bâtiments",
    "81.2": "Nettoyage",
    "81.3": "Aménagement paysager",
    "82.0": "Activités de soutien aux entreprises ; activités de bureau",
    # ── Section O : Administration Publique ──
    "84.1": "Administration générale, économique et sociale",
    "84.2": "Services de prérogative publique",
    "84.3": "Sécurité sociale obligatoire",
    # ── Section P : Enseignement ──
    "85.1": "Enseignement préscolaire et primaire",
    "85.2": "Enseignement secondaire",
    "85.3": "Enseignement supérieur",
    "85.4": "Formation professionnelle et autres activités d'enseignement",
    # ── Section Q : Santé et Action Sociale ──
    "86.1": "Activités hospitalières",
    "86.2": "Activités des médecins et des dentistes",
    "86.9": "Autres activités pour la santé humaine",
    "87.0": "Activités d'hébergement médico-social et social",
    "88.0": "Action sociale sans hébergement",
    # ── Section R : Activités Artistiques, Sportives et Récréatives ──
    "90.0": "Activités créatives, artistiques et de spectacle",
    "91.0": "Conservation et valorisation du patrimoine",
    "92.0": "Organisation de jeux de hasard et d'argent",
    "93.1": "Activités sportives",
    "93.2": "Activités récréatives et de loisirs",
    # ── Section S : Autres Activités de Services ──
    "94.1": "Activités des organisations économiques et patronales",
    "94.2": "Activités des syndicats de travailleurs",
    "94.9": "Autres activités des organisations associatives",
    "95.1": "Réparation d'ordinateurs et d'équipements de communication",
    "95.2": "Réparation de biens personnels et domestiques",
    "96.0": "Fourniture d'autres services personnels",
    # ── Section T : Activités Spéciales des Ménages ──
    "97.0": "Activités des ménages en tant qu'employeurs de personnel domestique",
    "98.0": "Activités indifférenciées autoproduites des ménages",
    # ── Section U : Organisations Extraterritoriales ──
    "99.0": "Activités des organisations extraterritoriales",
}


def get_divisions_for_section(section_code):
    """Retourne les divisions appartenant à une section donnée."""
    return {
        code: label
        for code, (sec, label) in DIVISIONS.items()
        if sec == section_code
    }


def get_groups_for_division(division_code):
    """Retourne les groupes appartenant à une division donnée."""
    return {
        code: label
        for code, label in GROUPS.items()
        if code.startswith(division_code + ".") or (code.startswith(division_code) and code[2] == ".")
    }
